### ISSUE TITLE
[Discussion] moment.js locale

### ISSUE THREAD

**Issue by xxzefgh** [Stichoza/awesome-georgia#18]
ჩემი აზრით 1-იანის გამოტოვება ქართულ ენაში არ "ჯდება", ვინაიდან ჩვენ არ გვაქვს a/an არტიკლი. მაგ: ```წამის წინ, დღის წინ...```, უმჯობესია ```1 წამის წინ, 1 დღის წინ...```
მაინტერესებს თქვენი აზრიც სანამ PR-ს გავაკეთებ.

**Comment by Stichoza** [comment]
ჰო ქართულში ცუდად ჟღერს. "წამის წინ" თითქოს სწორია, "დღის წინ" არასწორი :D რეავიცი აბა

**Comment by Stichoza** [comment]
"ემსაათში" დავამატოთ და "წეხან" :დ
