### ISSUE TITLE
Add iOS Repos

### ISSUE THREAD

**Issue by efremidze** [Stichoza/awesome-georgia#7]
Any iOS repos made in georgia?

**Comment by Stichoza** [comment]
Should be useful for Georgian developers, not just made in Georgia. So, any repos?

**Comment by efremidze** [comment]
All awesome lists are great references

**Comment by efremidze** [comment]
Oh so your saying repos made in georgia that are useful to developers. I thought u meant to include all useful repos disregarding their location. You should include repos made by georgian developers. It doesn't matter whether they live in georgia.

**Comment by Stichoza** [comment]
Location doesn't really matter. But I think you should re-read the description of this repo.
